

dubbo:
  application:
    name: summer-consumer
    qos-accept-foreign-ip: true
    qos-enable: true
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181
#  config-center:
#    address: zookeeper://127.0.0.1:2181
#  metadata-report:
server:
  port: 8081
#    address: zookeeper://127.0.0.1:2181