dubbo:
  application:
    name: summer-provider
    qos-enable: true
    qos-accept-foreign-ip: true
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181
  provider:
    filter: -exception
#  config-center:
#    address: zookeeper://127.0.0.1:2181
#  metadata-report:
#    address: zookeeper://127.0.0.1:2181